[package]
name = "zed-harnlang"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Zed extension for  LSP integration support for Harn language."
repository = "https://github.com/phgrey/zed-harnlang"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.3.0"
