id = "harn-lang"
name = "Harn Language"
version = "0.0.1"
schema_version = 1
authors = ["Sergey Semenov <phgrey@gmail.com>"]
description = "Harn language server, syntax and grammar support for Zed."
repository = "https://github.com/phgrey/zed-harnlang"


[grammars.harn]
repository = "https://github.com/burin-labs/harn"
path = "tree-sitter-harn"
commit = "fc5e9009c7b95b18d23d64c457d6c8f924e10515"

[language_servers.harnlang]
name = "Harn LSP"
languages = ["Harn"]
