id = "harnlang"
name = "Harn Language"
version = "0.1.1"
schema_version = 1
authors = ["Sergey Semenov <phgrey@gmail.com>"]
description = "Harn language syntax and grammar support for Zed."
repository = "https://github.com/phgrey/zed-harnlang"

[grammars.harn]
repository = "https://github.com/burin-labs/harn"
path = "tree-sitter-harn"
commit = "main"
